name: 'sales_insights'
version: '1.0.0'
config-version: 2

profile: 'sales_insights'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  git_sha: "{{ env_var('DBT_GIT_SHA', 'unknown') }}"

models:
  sales_insights:
    staging:
      +materialized: view
    marts:
      +materialized: table
